/* Static offline fixture. No request is made to obtain or update this data. */
window.PLAYGROUND_DATA = {
  schema_version: "1.0",
  run_id: "offline-demo",
  mode: "quantitative",
  selected_claim_id: "c1",
  claims: [
    {
      id: "c1",
      score: 0.69,
      text: "Abstract. We report the first method achieving AUC 0.87 on a held-out cohort.",
      evidence_span_ids: ["p1_b1", "p1_b4", "p2_b6"],
    },
    {
      id: "c2",
      score: 0.69,
      text: "Lowering the threshold to 0.30 raises sensitivity to 94% but reduces specificity.",
      evidence_span_ids: ["p2_b6"],
    },
    {
      id: "c3",
      score: 0.69,
      text: "The improvement over the baseline was consistent across all validation sites.",
      evidence_span_ids: ["p1_b4"],
    },
  ],
  spans: {
    p1_b1: {
      page: 1,
      kind: "paragraph",
      text: "We report an AUC of 0.87 at the operating threshold of 0.50, compared with 0.79 for the standard early-warning score in the same cohort.",
    },
    p1_b4: {
      page: 1,
      kind: "paragraph",
      text: "The effect was observed at three validation sites. The smallest cohort contained 312 encounters and showed an attenuated improvement.",
    },
    p2_b6: {
      page: 2,
      kind: "paragraph",
      text: "At a threshold of 0.30 sensitivity reached 94%, while specificity fell by 17 points. The false-alert estimate assumes a 6% base rate.",
    },
  },
  artifact: {
    primitive: "assumption_switchboard",
    title: "AUC 0.87 on a held-out cohort",
    controls: [],
    explanation: "각 스위치는 논문이 기대고 있는 조건 하나다.",
    warning: null,
    base_status: "strong",
    assumptions: [
      {
        id: "a1",
        claim_id: "c1",
        source: "paper_explicit",
        kind: "measurement",
        span_id: "p1_b1",
        text: "보고된 성능은 0.50 운영 임계값에서 측정된 값이다.",
        weakens_how: "임계값이 0.30으로 내려가면 민감도는 94%로 오르지만 특이도를 17점 잃어, 주장은 '이 운영점에서'라는 단서를 달아야 유지된다.",
      },
      {
        id: "a2",
        claim_id: "c1",
        source: "paper_implicit",
        kind: "generalization",
        span_id: "p1_b4",
        text: "효과 크기는 세 개 검증 사이트에서 비교 가능하다.",
        weakens_how: "사이트 간 비교 가능성이 없으면 결론은 대형 사이트에 한정되고, 가장 작은 코호트의 뒷받침은 빠진다.",
      },
      {
        id: "a3",
        claim_id: "c1",
        source: "paper_explicit",
        kind: "scope",
        span_id: "p1_b1",
        text: "대조군은 표준 조기경보점수이고 동일 코호트에서 평가됐다.",
        weakens_how: "다른 기준선과 비교하면 AUC 0.87의 개선폭 자체를 다시 계산해야 한다.",
      },
      {
        id: "a4",
        claim_id: "c1",
        source: "paper_explicit",
        kind: "implementation",
        span_id: "p2_b6",
        text: "허위경보 비율 추정은 6% 기저율을 전제한다.",
        weakens_how: "기저율이 낮은 병동에서는 참 1건당 허위경보 수가 커져, 임계값 하향의 운영 비용 주장이 약해진다.",
      },
    ],
    status_rules: [
      {
        assumption_id: "a1",
        status: "conditional",
        because: "성능은 0.50 운영점에서 잰 값이라, 임계값이 달라지면 민감도와 특이도의 교환비가 함께 달라진다.",
        attribution: { kind: "paper", span_id: "p1_b1", evidence_id: null },
      },
      {
        assumption_id: "a2",
        status: "weak",
        because: "사이트 간 효과가 비교 가능하지 않으면 결론은 대형 사이트에만 남고, 가장 작은 코호트는 뒷받침에서 빠진다.",
        attribution: { kind: "paper", span_id: "p1_b4", evidence_id: null },
      },
      {
        assumption_id: "a3",
        status: "conditional",
        because: "개선폭은 대조군이 표준 조기경보점수일 때의 값이라, 다른 기준선에서는 다시 계산해야 한다.",
        attribution: { kind: "pedagogical", span_id: null, evidence_id: null },
      },
      {
        assumption_id: "a4",
        status: "conditional",
        because: "기저율이 다르면 허위경보 계산의 운영 비용은 달라진다.",
        attribution: { kind: "pedagogical", span_id: null, evidence_id: null },
      },
    ],
    sources: { paper: "c1", external: 0 },
  },
  external: [],
  raw_events: [
    { id: "487a0804", ts: 1785575537.493, type: "stage_start", stage: "parse" },
    { id: "5879d54d", ts: 1785575537.493, type: "tool_call", name: "pdf.extract", arguments: { path: "fixtures/sample.pdf" } },
    { id: "1bd4d33b", ts: 1785575537.539, type: "tool_result", call_id: "5879d54d", result: { pages: 2, spans: 20, figures: 1, numbers: 32 }, error: null },
    { id: "83229360", ts: 1785575537.539, type: "decision", actor: "parse", text: "32개 수치를 근거 풀에 등록" },
    { id: "675f6990", ts: 1785575537.539, type: "stage_start", stage: "claims" },
    { id: "9849efa0", ts: 1785575537.54, type: "tool_call", name: "llm.structured", arguments: { role: "claim_mapper", schema: "Claim[]" } },
    { id: "677a15ef", ts: 1785575537.54, type: "decision", actor: "claims", text: "모델이 claims를 반환하지 않음 -> 수치 밀집 span을 후보로 사용" },
    { id: "07641dab", ts: 1785575537.54, type: "stage_start", stage: "score" },
    { id: "0bf18c10", ts: 1785575537.54, type: "stage_start", stage: "select" },
    { id: "d15997a5", ts: 1785575537.54, type: "decision", actor: "selector", text: "c1: 최고 interaction score로 자동 선택", claim_id: "c1", score: 0.69, policy: "highest_score_then_source_order", candidates: ["c1", "c2", "c3"] },
    { id: "40b91a7e", ts: 1785575537.54, type: "stage_end", stage: "select", seconds: 0, over_budget: false },
    { id: "f812620b", ts: 1785575537.54, type: "stage_start", stage: "assumptions" },
    { id: "a72cb556", ts: 1785575537.54, type: "stage_end", stage: "assumptions", seconds: 0 },
    { id: "bcde4910", ts: 1785575537.54, type: "stage_start", stage: "external" },
    { id: "f104ca28", ts: 1785575537.54, type: "tool_call", name: "llm.structured", arguments: { role: "external_query_planner", schema: "ExternalQueries" } },
    { id: "85ca031f", ts: 1785575537.54, type: "decision", actor: "verifier", text: "c1/support: 검색 결과 0건", claim_id: "c1", facet: "support", hits: 0, status: "empty" },
    { id: "0ccbe2ca", ts: 1785575537.54, type: "decision", actor: "verifier", text: "c1/contradict: 검색 결과 0건", claim_id: "c1", facet: "contradict", hits: 0, status: "empty" },
    { id: "9323057c", ts: 1785575537.54, type: "decision", actor: "verifier", text: "c1/boundary: 검색 결과 0건", claim_id: "c1", facet: "boundary", hits: 0, status: "empty" },
    { id: "2dc58a0d", ts: 1785575537.54, type: "decision", actor: "verifier", text: "c1/methodology: 검색 결과 0건", claim_id: "c1", facet: "methodology", hits: 0, status: "empty" },
    { id: "84ec5f07", ts: 1785575537.54, type: "stage_end", stage: "external", seconds: 0, over_budget: false },
    { id: "e963f8c8", ts: 1785575537.54, type: "stage_start", stage: "design" },
    { id: "446a25b2", ts: 1785575537.54, type: "decision", actor: "designer", text: "status 규칙 4개 확정 (가정 4개)", rules: { a1: "conditional", a2: "weak", a3: "conditional", a4: "conditional" } },
    { id: "2125b36b", ts: 1785575537.54, type: "stage_start", stage: "critic" },
    { id: "e4b13e79", ts: 1785575537.54, type: "decision", actor: "critic", text: "verdict PASS", result: "PASS", fatal_codes: [] },
    { id: "e8c1dd15", ts: 1785575537.54, type: "stage_end", stage: "critic", seconds: 0, over_budget: false },
    { id: "045b246f", ts: 1785575537.54, type: "stage_start", stage: "render" },
    { id: "d3773784", ts: 1785575537.54, type: "stage_end", stage: "render", seconds: 0 },
  ],
};
